version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: cartbuddy-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.4
    container_name: cartbuddy-redis
    restart: always
    ports:
      - '6379:6379'
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--loglevel',
        'warning',
      ]

volumes:
  mongo-data:
